### PR TITLE
Adding storageClassName support for Serviceability

### LINKED ISSUE #187: serviceability storageClassName operator addition
## Feature Request
Add serviceability.storageClassName to the operator so I can overwrite the default storageClass that is used in my cluster

### Describe the solution you'd like
In lots of cluster block storage is the default solution

With the addition of serviceability.storageClassName I could overwrite the default storageClass and I don't have to manage the pvc on my own.

serviceability:
  size: 1G
  storageClassName: nfsdisk

### PR DESCRIPTION
**Pull request by NissesSenap**
**What this PR does / why we need it?**:

- To be able to overwrite the default storageClass for Serviceability 

**Does this PR introduce a user-facing change?**

- [x] User guide
- [ ] `CHANGELOG.md`

**Which issue(s) this PR fixes**:

Fixes #187

### CODE REVIEW

**Comment by NissesSenap** [comment]
Sorry for changes in rows that I haven't performed any functional changes to, formaters...
If you want I can revert those changes and re-add mine.

**Comment by JusteenR** [comment]
@NissesSenap If you could revert those changes and re-add your code that would be great and run the `make generate` command, also do you mind if I make changes to if statement to make it more concise?

**Comment by NissesSenap** [comment]
Sure I will fix it later tonight.
Please do, I know they are far from perfect.
Thanks for your help

**Comment by NissesSenap** [comment]
@JusteenR 
I have done what you asked and removed the extra lines I had performed changes in.

But I'm not sure it's a good idea that I perform the generate and push that.
I'm using a rather new version of operator-sdk and when I have commited to other operators I have seen a few interesting changes between the versions.

In those cases one of the code owners have perform the generator to keep it cosistent.

When I run the make generate command I get the following error:
```
./scripts/installers/install-operator-sdk.sh v0.15.2
operator-sdk version: "v0.18.1", commit: "7bf7b6886d647dc202525daec16fab67dcc52a3d", kubernetes version: "v1.18.2", go version: "go1.13.6 linux/amd64"
operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [openliberty:[v1beta1], ] 
INFO[0037] Code-generation complete.                    
operator-sdk generate openapi
The 'operator-sdk generate' command invokes a specific generator to generate
code or manifests.

Usage:
  operator-sdk generate [command]

Available Commands:
  bundle      Generates bundle data for the operator
  crds        Generates CRDs for API's
  csv         Generates a ClusterServiceVersion YAML file for the operator
  k8s         Generates Kubernetes code for custom resource

Flags:
  -h, --help   help for generate

Global Flags:
      --verbose   Enable verbose logging

Use "operator-sdk generate [command] --help" for more information about a command.
# Remove `x-kubernetes-int-or-string: true` from CRD. Causing issues on cluster with older k8s
sed -i '' '/x\-kubernetes\-int\-or\-string\: true/d' deploy/crds/openliberty.io_openlibertyapplications_crd.yaml
sed: can't read /x\-kubernetes\-int\-or\-string\: true/d: No such file or directory

```
I changed in the Makefile and changed 
operator-sdk generate openapi crds
Since I assume that's what you want.

Then I get this issue:
```
# Remove `x-kubernetes-int-or-string: true` from CRD. Causing issues on cluster with older k8s
sed -i '' '/x\-kubernetes\-int\-or\-string\: true/d' deploy/crds/openliberty.io_openlibertyapplications_crd.yaml
sed: can't read /x\-kubernetes\-int\-or\-string\: true/d: No such file or directory
```

This wtth sed have never been my strong thing but I assume you just remove the line 
"x-kubernetes-int-or-string: true"

But for some reason the sed dosen't work from my, I tried in both zsh and bash.

I see now that the travis job failes.
I will write something that cleans up the "x-kubernetes-int-or-string: true"

**Comment by NissesSenap** [comment]
Something something mac...

So for anyone using Linux the make file have:
`sed -i '' '/x\-kubernetes\-int\-or\-string\: true/d' deploy/crds/openliberty.io_openlibertyapplications_crd.yaml`

You should change to:
`sed -i '/x\-kubernetes\-int\-or\-string\: true/d' deploy/crds/openliberty.io_openlibertyapplications_crd.yaml`

Tried to learn the syntax for ifeq in makefile and add check which os you are running to fix this for other people but I couldn't get it to work and it's starting to be late so if anyone is ninja at makefiles please add a if check.

**Comment by JusteenR** [comment]
@NissesSenap 
The changes look good now, implementing the changes in the utils.go like below would remove repeated code.

```
// CreateServiceabilityPVC creates PersistentVolumeClaim for Serviceability
func CreateServiceabilityPVC(instance *openlibertyv1beta1.OpenLibertyApplication) *corev1.PersistentVolumeClaim {
	persistentVolume := &corev1.PersistentVolumeClaim{
		ObjectMeta: metav1.ObjectMeta{
			Name:        instance.Name + "-serviceability",
			Namespace:   instance.Namespace,
			Labels:      instance.GetLabels(),
			Annotations: instance.GetAnnotations(),
		},
		Spec: corev1.PersistentVolumeClaimSpec{
			Resources: corev1.ResourceRequirements{
				Requests: corev1.ResourceList{
					corev1.ResourceStorage: resource.MustParse(instance.GetServiceability().GetSize()),
				},
			},
			AccessModes: []corev1.PersistentVolumeAccessMode{
				corev1.ReadWriteMany,
				corev1.ReadWriteOnce,
			},
		},
	}
	if instance.GetServiceability().GetStorageClassName() != nil {
		persistentVolume.Spec.StorageClassName = &instance.GetServiceability().StorageClassName
	}
	return persistentVolume
}
```

**Comment by arthurdm** [comment]
thank you @NissesSenap and @JusteenR!

**Pull request merged**
